# Generated by Django 4.2.1 on 2024-04-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='today_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
